ROOT := $(abspath $(dir $(lastword $(MAKEFILE_LIST)))../..)

PROPS := props.v
REF   := $(ROOT)/solutions/02-reasoning-about-time/props.v

TASKS := good:pass bad1:fail bad2:fail bad3:fail bad4:fail bad5:fail cover:pass

include $(ROOT)/mk/formal.mk
